export const INDUSTRY_OPTIONS = [
  { value: 'SAP Consulting', label: 'SAP Consulting' },
  { value: 'IT Services', label: 'IT Services' },
  { value: 'Manufacturing', label: 'Manufacturing' },
  { value: 'Telecommunications', label: 'Telecommunications' },
  { value: 'Banking', label: 'Banking' },
  { value: 'Healthcare', label: 'Healthcare' },
  { value: 'Retail', label: 'Retail' },
  { value: 'Energy & Utilities', label: 'Energy & Utilities' },
  { value: 'Oil & Gas', label: 'Oil & Gas' },
  { value: 'Information Technology', label: 'Information Technology' },
  { value: 'Consulting', label: 'Consulting' },
  { value: 'Other', label: 'Other' },
] as const

export const countries = [
  { name: "Afghanistan", isoCode: "AF", phonePrefix: "+93", currencyCode: "AFN", currencySymbol: "؋", flag: "🇦🇫" },
  { name: "Albania", isoCode: "AL", phonePrefix: "+355", currencyCode: "ALL", currencySymbol: "L", flag: "🇦🇱" },
  { name: "Algeria", isoCode: "DZ", phonePrefix: "+213", currencyCode: "DZD", currencySymbol: "د.ج", flag: "🇩🇿" },
  { name: "Andorra", isoCode: "AD", phonePrefix: "+376", currencyCode: "EUR", currencySymbol: "€", flag: "🇦🇩" },
  { name: "Angola", isoCode: "AO", phonePrefix: "+244", currencyCode: "AOA", currencySymbol: "Kz", flag: "🇦🇴" },
  { name: "Argentina", isoCode: "AR", phonePrefix: "+54", currencyCode: "ARS", currencySymbol: "$", flag: "🇦🇷" },
  { name: "Armenia", isoCode: "AM", phonePrefix: "+374", currencyCode: "AMD", currencySymbol: "֏", flag: "🇦🇲" },
  { name: "Australia", isoCode: "AU", phonePrefix: "+61", currencyCode: "AUD", currencySymbol: "$", flag: "🇦🇺" },
  { name: "Austria", isoCode: "AT", phonePrefix: "+43", currencyCode: "EUR", currencySymbol: "€", flag: "🇦🇹" },
  { name: "Azerbaijan", isoCode: "AZ", phonePrefix: "+994", currencyCode: "AZN", currencySymbol: "₼", flag: "🇦🇿" },
  { name: "Bahrain", isoCode: "BH", phonePrefix: "+973", currencyCode: "BHD", currencySymbol: ".د.ب", flag: "🇧🇭" },
  { name: "Bangladesh", isoCode: "BD", phonePrefix: "+880", currencyCode: "BDT", currencySymbol: "৳", flag: "🇧🇩" },
  { name: "Belgium", isoCode: "BE", phonePrefix: "+32", currencyCode: "EUR", currencySymbol: "€", flag: "🇧🇪" },
  { name: "Brazil", isoCode: "BR", phonePrefix: "+55", currencyCode: "BRL", currencySymbol: "R$", flag: "🇧🇷" },
  { name: "Canada", isoCode: "CA", phonePrefix: "+1", currencyCode: "CAD", currencySymbol: "$", flag: "🇨🇦" },
  { name: "China", isoCode: "CN", phonePrefix: "+86", currencyCode: "CNY", currencySymbol: "¥", flag: "🇨🇳" },
  { name: "France", isoCode: "FR", phonePrefix: "+33", currencyCode: "EUR", currencySymbol: "€", flag: "🇫🇷" },
  { name: "Germany", isoCode: "DE", phonePrefix: "+49", currencyCode: "EUR", currencySymbol: "€", flag: "🇩🇪" },
  { name: "India", isoCode: "IN", phonePrefix: "+91", currencyCode: "INR", currencySymbol: "₹", flag: "🇮🇳" },
  { name: "Indonesia", isoCode: "ID", phonePrefix: "+62", currencyCode: "IDR", currencySymbol: "Rp", flag: "🇮🇩" },
  { name: "Italy", isoCode: "IT", phonePrefix: "+39", currencyCode: "EUR", currencySymbol: "€", flag: "🇮🇹" },
  { name: "Japan", isoCode: "JP", phonePrefix: "+81", currencyCode: "JPY", currencySymbol: "¥", flag: "🇯🇵" },
  { name: "Malaysia", isoCode: "MY", phonePrefix: "+60", currencyCode: "MYR", currencySymbol: "RM", flag: "🇲🇾" },
  { name: "Mexico", isoCode: "MX", phonePrefix: "+52", currencyCode: "MXN", currencySymbol: "$", flag: "🇲🇽" },
  { name: "Netherlands", isoCode: "NL", phonePrefix: "+31", currencyCode: "EUR", currencySymbol: "€", flag: "🇳🇱" },
  { name: "New Zealand", isoCode: "NZ", phonePrefix: "+64", currencyCode: "NZD", currencySymbol: "$", flag: "🇳🇿" },
  { name: "Nigeria", isoCode: "NG", phonePrefix: "+234", currencyCode: "NGN", currencySymbol: "₦", flag: "🇳🇬" },
  { name: "Norway", isoCode: "NO", phonePrefix: "+47", currencyCode: "NOK", currencySymbol: "kr", flag: "🇳🇴" },
  { name: "Pakistan", isoCode: "PK", phonePrefix: "+92", currencyCode: "PKR", currencySymbol: "₨", flag: "🇵🇰" },
  { name: "Philippines", isoCode: "PH", phonePrefix: "+63", currencyCode: "PHP", currencySymbol: "₱", flag: "🇵🇭" },
  { name: "Qatar", isoCode: "QA", phonePrefix: "+974", currencyCode: "QAR", currencySymbol: "ر.ق", flag: "🇶🇦" },
  { name: "Russia", isoCode: "RU", phonePrefix: "+7", currencyCode: "RUB", currencySymbol: "₽", flag: "🇷🇺" },
  { name: "Saudi Arabia", isoCode: "SA", phonePrefix: "+966", currencyCode: "SAR", currencySymbol: "ر.س", flag: "🇸🇦" },
  { name: "Singapore", isoCode: "SG", phonePrefix: "+65", currencyCode: "SGD", currencySymbol: "$", flag: "🇸🇬" },
  { name: "South Africa", isoCode: "ZA", phonePrefix: "+27", currencyCode: "ZAR", currencySymbol: "R", flag: "🇿🇦" },
  { name: "South Korea", isoCode: "KR", phonePrefix: "+82", currencyCode: "KRW", currencySymbol: "₩", flag: "🇰🇷" },
  { name: "Spain", isoCode: "ES", phonePrefix: "+34", currencyCode: "EUR", currencySymbol: "€", flag: "🇪🇸" },
  { name: "Sri Lanka", isoCode: "LK", phonePrefix: "+94", currencyCode: "LKR", currencySymbol: "₨", flag: "🇱🇰" },
  { name: "Sweden", isoCode: "SE", phonePrefix: "+46", currencyCode: "SEK", currencySymbol: "kr", flag: "🇸🇪" },
  { name: "Switzerland", isoCode: "CH", phonePrefix: "+41", currencyCode: "CHF", currencySymbol: "CHF", flag: "🇨🇭" },
  { name: "Thailand", isoCode: "TH", phonePrefix: "+66", currencyCode: "THB", currencySymbol: "฿", flag: "🇹🇭" },
  { name: "Turkey", isoCode: "TR", phonePrefix: "+90", currencyCode: "TRY", currencySymbol: "₺", flag: "🇹🇷" },
  { name: "United Arab Emirates", isoCode: "AE", phonePrefix: "+971", currencyCode: "AED", currencySymbol: "د.إ", flag: "🇦🇪" },
  { name: "United Kingdom", isoCode: "GB", phonePrefix: "+44", currencyCode: "GBP", currencySymbol: "£", flag: "🇬🇧" },
  { name: "United States", isoCode: "US", phonePrefix: "+1", currencyCode: "USD", currencySymbol: "$", flag: "🇺🇸" },
  { name: "Vietnam", isoCode: "VN", phonePrefix: "+84", currencyCode: "VND", currencySymbol: "₫", flag: "🇻🇳" },
  // ... (Remaining countries omitted for brevity — ask if you want full 195 in one copy-paste block)
];