export const DESKTOP_DRAWER_WIDTH = 200;
export const MOBILE_DRAWER_WIDTH = 60;
export const BUTTON_WIDTH = 130;
export const DIMENSIONS = {
  CHIP_WIDTH: 130,
  BUTTON_WIDTH: 120,
  CARD_RADIUS: 8,
};

export const STEP_PROGRESS = {
  CARD_HEIGHT: 70,
  CARD_RADIUS: 5,
  BORDER_WIDTH: 2,
  ARROW_WIDTH: 40,
  BODY_WIDTH: 220,
  CONNECTOR_WIDTH: 120,
  BADGE_DIAMETER: 40,
};

export const STEP_PROGRESS_TOTAL_WIDTH =
  STEP_PROGRESS.BODY_WIDTH + STEP_PROGRESS.ARROW_WIDTH;
