export const API_ROUTES = {
  //auth routes
  SIGNUP_CLIENT: "/auth/signup/user",
  LOGIN: "/auth/login",
  SIGNUP_CONSULTANT: "/auth/signup/consultant",
  SEND_VERIFICATION_EMAIL: "/auth/send-verification-email",
  VERIFY_EMAIL: (token:string) => `/auth/verify-email?token=${token}`,
  FORGOT_PASSWORD: "auth/forgot-password",
  RESET_PASSWORD: "auth/reset-password",

  //user:
  GET_ME: "/users/me",
  UPDATE_PASSWORD: "/users/change-password",

  CLIENT_CONSULTANTS: "/clients/consultants",
  PROJECT_CREATE: "/projects/create",
  ADD_PROJECT_DETAILS: "/projects",
  UPDATE_PROJECT: "/projects",
  MILESTONE_CREATE: "/projects",
  GET_PROJECT_MILESTONE: "/projects",
  GET_PROJECT_PAYMENTS: "/projects",
  GET_MILESTONE_TASKS: "/projects/milestones",
  MILESTONE_TASKS_CREATE: "/projects/milestones",
  UPDATE_MILESTONE: "/projects/milestones",
  UPDATE_TASKS: "/projects/tasks",
  SHORTLIST_CANDIDATES: "/projects",
  PROJECT_CONSULTANTS: "/projects",
  MEETING_INVITE: "/common/meeting-invite",
  GET_CONSULTANT_LEVELS: "/common/consultant-levels",
  UPDATE_CONSULTANT_STATUS: "/projects/consultant/status",
  CLIENT_PAYMENTS: "/clients/payments",
  CLIENT_PROJECTS: "/clients/projects",
  SEND_MESSAGE: "/chat/send",
  GET_CONVERSATION: "/chat/conversation",
  MARK_READ: "/chat/mark-read",
  INBOX: "/chat/inbox",
  PROJECT_CHAT: "/chat/project",
  USERS: "/users",
  CLIENT_MEETINGS: "/common/meetings",
  MEETING_STATUS: "/common/meeting-status",
  GET_PROJECT_DETAILS: "/projects",
  CONSULTANT_PROJECTS: "/consultants/projects",
  CONSULTANT_PAYMENTS: "/consultants/monthly-bills",
  CONSULTANT_HOUR_LOGS: "/consultants/hour-logs",
  CONSULTANT_DASHBOARD: "/consultants/dashboard",
  CONSULTANT_DASHBOARD_V2: "/consultants/v2/dashboard",
  SAP_MODULES: "/common/sap-modules",
  SAP_OTHER_MODULES: "/common/module/tree",
  COMMON_MEETINGS: "/common/meetings",
  ADMIN_STATS: "/admin/stats",
  ADMIN_PROJECTS: "/admin/projects",
  ADMIN_CONSULTANTS: "/admin/consultants/all",
  UPDATE_ADMIN_CONSULTANT_STATUS: "/admin/consultants",
  ADMIN_CLIENTS: "/admin/clients/all",
  UPDATE_ADMIN_CLIENT_STATUS: "/admin/clients",
  PDF_READER: "/common/pdf-reader",
  COMMON_UPLOAD: "/common/upload",
  PROJECT_DOCUMENT_UPLOAD: "/projects/documents/upload",
  CONSULTANT_PROFILE: "/consultants/me",
  UPDATE_CONSULTANT_PROFILE: `/consultants/`,
  DELETE_CONSULTANT_PROFILE: "/consultants/profile",
  GET_CONSULTANT_SCHEDULE: "/consultants/schedule",
  POST_CONSULTANT_SCHEDULE: "/consultants/schedule",
  CONSULTANT_STATS: "/consultants/stats",
  CONSULTANT_RIGHT_SIDEBAR: "/consultants/left-sidebar",
  CLIENT_STATS: "/clients/stats",
  CLIENT_PROFILE: "/clients/me",
  UPDATE_CLIENT_PROFILE: "/clients",
  MODULES: "/common/module",
  ADMIN_INDUSTRIES: "/admin/industries",
  GET_INDUSTRIES: "/common/industry",
  GET_EXPERTISE_LEVELS: "/consultants/experience-levels",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_CONSULTANT_PAYMENTS: "/admin/consultant/payments",
  ADMIN_CONSULTANT_PAYMENT: "/admin/consultant/payment",

};
