export const API_ROUTES = {
  SIGNUP_CLIENT: "/auth/signup/user",
  LOGIN: "/auth/login",
  SIGNUP_CONSULTANT: "/auth/signup/consultant",
  CLIENT_CONSULTANTS: "/clients/consultants",
  PROJECT_CREATE: "/projects/create",
  PROJECT_UPDATE: "/projects",
  UPDATE_PROJECT: "/projects",
  MILESTONE_CREATE: "/projects",
  GET_MILESTONE_TASKS: "/projects/milestones",
  MILESTONE_TASKS_CREATE: "/projects/milestones",
  UPDATE_MILESTONE: "/projects/milestones",
  UPDATE_TASKS: "/projects/tasks",
  SHORTLIST_CANDIDATES: "/projects",
  PROJECT_CONSULTANTS: "/projects",
  MEETING_INVITE: "/common/meeting-invite",
  GET_CONSULTANT_LEVELS: "/common/consultant-levels",
  UPDATE_CONSULTANT_STATUS: "/projects/consultant/status",
  CLIENT_PAYMENTS: "/clients/payments",
  CLIENT_PROJECTS: "/clients/projects",
};
