export const APP_ROUTES = {
  HOME: "/",
  VERIFY_EMAIL: "/verify-email",
  RESET_PASSWORD: "/reset-password",
  LOGIN: "/auth/login",
  SIGNUP_SELECT: "/auth/signup-select",
  SIGNUP: "/auth/signup",
  TEAMBUILDER: "/teambuilder",
  CONTACT_US: "/contact-us",
  CONSULTANT: {
    CHANGE_PASSWORD: "/consultant/change-password",
    DASHBOARD: "/consultant/dashboard",
    PROJECTS: "/consultant/projects",
    INTERVIEWS: "/consultant/interviews",
    PAYMENTS: "/consultant/payments",
    DOCUMENTS: "/consultant/documents",
    PROFILE: "/consultant/profile",
    ACCOUNT: "/consultant/account",
    CALENDAR: "/consultant/calendar",
  },
  CLIENT: {
    DASHBOARD: "/client/dashboard",
    PROJECTS: "/client/projects",
    INTERVIEWS: "/client/interviews",
    PAYMENTS: "/client/payments",
    DOCUMENTS: "/client/documents",
    PROFILE: "/client/profile",
    CONSULTANT: "/client/consultant",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    PROJECTS: "/admin/projects",
    INTERVIEWS: "/admin/interviews",
    PAYMENTS: "/admin/payments",
    PROFILE: "/admin/profile",
    CONSULTANTS: "/admin/consultant",
    CLIENT: "/admin/client",
    NOTIFICATIONS: "/admin/notifications"
  },
};
