export const APP_ROUTES = {
  HOME: "/",
  LOGIN: "/",
  SIGNUP_SELECT: "/auth/signup-select",
  SIGNUP: "/auth/signup",
  TEAMBUILDER: "/teambuilder",
  
  CONSULTANT: {
    DASHBOARD: "/consultant/dashboard",
    PROJECTS: "/consultant/projects",
    INTERVIEWS: "/consultant/interviews",
    PAYMENTS: "/consultant/payments",
    DOCUMENTS: "/consultant/documents",
    PROFILE: "/consultant/profile",
    CALENDAR: "/consultant/calendar",
  },
  CLIENT: {
    DASHBOARD: "/client/dashboard",
    PROJECTS: "/client/projects",
    INTERVIEWS: "/client/interviews",
    PAYMENTS: "/client/payments",
    DOCUMENTS: "/client/documents",
    PROFILE: "/client/profile",
    CONSULTANT: "/client/consultant",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    PROJECTS: "/admin/projects",
    INTERVIEWS: "/admin/interviews",
    PAYMENTS: "/admin/payments",
    PROFILE: "/admin/profile",
    CONSULTANTS: "/admin/consultant",
    CLIENT: "/admin/client",
  },
};
